name: Package
# TODO... publish to PyPI

on:
  push:
    branches: [ main ]
    tags: '**'
  workflow_run:
    workflows: [ "Lint and Test" ]
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest
    # environment: pypi
    # permissions:
    #   id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        uses: astral-sh/setup-uv@v5
      - name: Install project
        run: uv sync --all-groups
      - name: Build wheel
        run: uv build --wheel
      # - name: Publish package
      #   run: uv publish
      - name: Upload built package as artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/**

